# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ef5058a163c74883717e672360c9e3a1f46bda5ddf5e66146029384f3f0decc02ebb65d8dfb33c638048319ff8db382ec45e0971665da2b63835cc328cbebbe

test:
  secret_key_base: 6d3cd6139ba3a0f57a6f712f4b64beaa09448450c3c4eefb652ac9bf6810125c4c7b68a251c40723664385d8bd8385313fd8164f9c6867ed2c443b8de3b55f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
